"""Add is_admin to User model

Revision ID: 2086434c9f55
Revises: 8dbfa9dcdf83
Create Date: 2024-10-07 22:45:02.354174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2086434c9f55'
down_revision = '8dbfa9dcdf83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
